### ISSUE TITLE
fader resolution for Base (Base2?) 

### ISSUE THREAD

**Issue by aklinbail** [LividInstruments/Bitwig#1]
Hi
The fader resolution for the BASE is stuck at low.. 
Someone has manually worked out the code change.. on this page 

https://www.kvraudio.com/forum/viewtopic.php?p=6445025

open the script in a text editor and change line 78 to:
CODE: SELECT ALL
const DISABLECAPFADERNOTES = "F0 00 01 61 "+PRODUCTID+" 3C 09 09 09 09 09 09 09 09 09 F7";

can the scripts please be updated with this functionality... save us doing the hack on each machine we run bitwig.

**Comment by nyboer** [comment]
fixed!

**Comment by LividInstruments** [comment]
fixed!

**Comment by aklinbail** [comment]
Hi, 
I notice you only updated the code for the BaseII.. I have an original Base.
